🤖 Merge PR #62070 fix: antlr4: add missing export of `tree` submodule by @gthb
* fix: add missing tree export

ANTLR4-generated visitor classes extend antlr4.tree.ParseTreeVisitor which is
missing in the type declarations. Adding this export fixes that.

* test: add test for antlr4.tree resolution

This test requires importing `antlr4` itself, not destructured:

```ts
import * as antlr4 from 'antlr4';

export default class ExcelVisitor extends antlr4.tree.ParseTreeVisitor {}
```

whereas the existing tests assume a destructuring import:

```ts
import { Interval, InputStream, CommonTokenStream, Lexer, Parser, ParserRuleContext } from 'antlr4';
```

so this commit just adds the above `import * as` line, and that makes `npm run
test antlr4` fail with this:

```
Error: /Users/gthb/git/DefinitelyTyped/types/antlr4/antlr4-tests.ts:2:1
ERROR: 2:1  no-duplicate-imports  Multiple imports from 'antlr4' can be combined into one.
```

... which does not appear to be true (or at least I can't find a way to combine
these imports that works). Still committing in the current form to leave a
clear separation of steps in commit history and show test failures in the PR
history. Then a subsequent commit will replace the destructuring import with a
whole-module import and update references in existing tests.

* test: fix antlr4 test, using a whole-module import

Replace destructuring import with whole-module import and update references in
existing tests. This appears to be necessary in order to test the resolution of
`antlr4.tree` which is the form in which the `tree` submodule is imported in
visitor class modules generated by ANTLR4.