Fixed two any type annotations (#9553)
Fixed two TypeScript errors when noImplicitAny is set to true:

    .../typings/globals/pouchdb/pouch/index.d.ts(178,14): error TS7006: Parameter 'any' implicitly has an 'any' type.
    .../typings/globals/pouchdb/pouch/index.d.ts(229,18): error TS7010: 'emit', which lacks return-type annotation, implicitly has an 'any' return type.