rename `createBrowserHistory` to `createHistory `
`createBrowserHistory ` was only introduced in the `history@4.0.0-1`
prior to that the `createHistory` was used. So if you will install
`@types/history@^2.0.0` and `history@^2.0.0`(or even `^3.x.x`) it will
break with the next error:
```
./src/client/history.ts
(1,10): error TS2305: Module ‘”/@types/history/index"' has no exported
member 'createHistory'.
```
This commit brings the `createHistory` back thus solves the issue for
`history@^2.x.x` and `history@^3.x.x`.