accept Window as argument to JQueryStatic (#37567)
Users write code like:
  angular.element(window)
  angular.element($window)  // IWindowService

but this fails with a type error under TypeScript 3.5, due to a change
in the type of of Window.  (Previously the only reason it compiled is
that Window was matching the ArrayLike<Element> param.)

Note that if you run the tests, the definition of JQueryStatic here
in the JQLite typings declaration-merges with the full JQuery
definition, which accepts any (!) so there is no type error.  But if
you use just this library without JQuery, the type errors without my
fix look like:

angular-tests.ts:788:17 - error TS2345: Argument of type 'Window' is not assignable to parameter of type 'string | Element | Document | JQuery | ArrayLike<Element> | (() => void)'.
  Type 'Window' is missing the following properties from type 'Document': activeElement, alinkColor, all, anchors, and 147 more.

788 angular.element(window);
                    ~~~~~~

angular-tests.ts:790:17 - error TS2345: Argument of type 'IWindowService' is not assignable to parameter of type 'string | Element | Document | JQuery | ArrayLike<Element> | (() => void)'.
  Type 'IWindowService' is missing the following properties from type 'Document': activeElement, alinkColor, all, anchors, and 147 more.